Add note on how to create a service account for GCP
cloudskiff/driftctl-docs pull request #104
Opened 2021-09-06 15:28 UTC by eliecharra

2021-09-06 16:06 UTC, sjourdan requested changes

2021-09-06 16:06 UTC, sjourdan commented on docs/providers/google/authentication.mdx
> +Since driftctl use Cloud Asset API, using a service account is **mandatory**.
...driftctl uses ...

2021-09-06 16:06 UTC, sjourdan commented on docs/providers/google/authentication.mdx
> +Please refer to [the guide](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials) from terraform official documentation on how to create a se
...from the Terraform official...

2021-09-07 08:51 UTC, eliecharra commented
@sjourdan Updated the doc and removed terraform related stuff since we do not support theses env vars (terraform custom logic)

2021-09-07 12:53 UTC, sjourdan approved these changes
sounds safe for new users! LGTM

2021-09-07 13:31 UTC, merged