Add add aws_appautoscaling_scheduled_action resource
cloudskiff/driftctl-docs pull request #120
Opened 2021-09-24 08:46 UTC by sundowndev

2021-10-01 09:06 UTC, eliecharra approved these changes

2021-10-01 09:06 UTC, eliecharra commented
@sundowndev Conflicts must be resolved

2021-10-05 09:19 UTC, wbeuil requested changes

2021-10-05 09:19 UTC, wbeuil commented on docs/providers/aws/resources.mdx
> +| aws_appautoscaling_scheduled_action | ✅ |
Need to change since it's not deep-mode compliant anymore/

2021-10-06 13:29 UTC, eliecharra approved these changes

2021-10-06 13:38 UTC, merged