Add usage with URL
cloudskiff/driftctl-docs pull request #17
Opened 2021-03-16 11:05 UTC by sundowndev

### References

- https://github.com/cloudskiff/driftctl/pull/335

2021-03-16 11:15 UTC, wbeuil requested changes

2021-03-16 11:15 UTC, wbeuil commented on docs/usage/cmd/scan/iac-source.mdx
> +  - HTTP `--from tfsate+http://my-url/state.tfsate`
`HTTP:` and `tfstate`

2021-03-16 11:15 UTC, wbeuil commented on docs/usage/cmd/scan/iac-source.mdx
> +$ driftctl scan --from tfsate+https://example.com/terraform.tfsate
`tfstate`

2021-03-16 14:17 UTC, sundowndev commented on docs/usage/cmd/scan/iac-source.mdx
> +$ driftctl scan --from tfsate+https://example.com/terraform.tfsate
Not sure what you're referring to, do you mean `driftctl scan --from tfsate://example.com/terraform.tfsate` ?

2021-03-16 14:19 UTC, wbeuil commented on docs/usage/cmd/scan/iac-source.mdx
> +$ driftctl scan --from tfsate+https://example.com/terraform.tfsate
You wrote `tfsate` instead of `tfstate` everywhere :)

2021-03-16 14:29 UTC, sundowndev commented on docs/usage/cmd/scan/iac-source.mdx
> +$ driftctl scan --from tfsate+https://example.com/terraform.tfsate
Oh right, thanks :smile:

2021-03-16 14:44 UTC, wbeuil reviewed
I'm good with that for the moment, we should wait for your second part on header flags to go further with this PR.

2021-03-18 09:28 UTC, wbeuil approved these changes
LGTM

2021-03-18 10:42 UTC, merged