Issue 285: Add documentation to integrate driftctl to Jenkins
cloudskiff/driftctl-docs pull request #20
Opened 2021-03-18 12:29 UTC by lotoussa

2021-03-18 13:46 UTC, sundowndev commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "dctlenv/bin/driftctl scan"
Shouldn't we simply recommend the official release instead? Just asking, because it appears dctlenv is mostly used for test environments, isn't it ?

2021-03-18 15:00 UTC, wbeuil commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "dctlenv/bin/driftctl scan"
We use it in the other CI "plugins" (GitHub Action and CircleCi before its refacto with our docker image). Hence it was more a way to be in sync with the others.

It depends on what you are referring to by "test" environments ? I find it convenient here to have a tool that downloads and checks on signatures with minimal LOC.

2021-03-18 15:23 UTC, sundowndev commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "dctlenv/bin/driftctl scan"
Alright, thanks for the answer!

2021-03-18 15:24 UTC, sundowndev approved these changes
LGTM

2021-03-18 16:52 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +		AWS_DEFAULT="aws_profile"
You mean `AWS_PROFILE` ?

2021-03-18 16:52 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "git clone https://github.com/wbeuil/dctlenv || true"
What is the goal of `|| true` ?

2021-03-18 16:52 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
Why adding $HOME to the path ?

2021-03-18 22:56 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +		AWS_DEFAULT="aws_profile"
Yes. And i'm thinking, if it's working with this spelling error it's should mean this env var is useless ?
I can test it tomorrow, i need to reinstall my test env

2021-03-18 22:59 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "git clone https://github.com/wbeuil/dctlenv || true"
If dctlenv repository is already cloned it stop the pipeline because git clone return error code. Like this it always return success.
If necessary i can change that with an if statement that check if the repository already exist before git clone.

2021-03-18 23:02 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
To find the dctlenv / driftctl executable. Honestly it seem to be the simple way to setup this.

2021-03-19 10:39 UTC, sundowndev commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
You can also add $HOME/dctlenv/bin to the $PATH so you use executables without specifying /bin/ path

2021-03-19 10:43 UTC, sundowndev commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "git clone https://github.com/wbeuil/dctlenv || true"
Why the repo would be already cloned if it's inside a unique pipeline run ? I haven't used jenkins much so may be it works differently than other CI systems

2021-03-19 10:45 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
Exactly, actually only adding `$HOME` to the path is useless as you never use a binary from `$HOME` directory

2021-03-19 10:47 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "git clone https://github.com/wbeuil/dctlenv || true"
Yeah we need to dig into this. BTW piping the git clone with `|| true` may hide us some real git clone issues. It is a catch-all and this is not what we want there.

Something like this may be more appropriate : `which dctlenv || git clone ... `

2021-03-19 10:47 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +						sh "git clone https://github.com/wbeuil/dctlenv || true"
In my work case the pipeline run wasn't unique

2021-03-19 10:47 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +		AWS_DEFAULT="aws_profile"
You can remove this variable as you never set a profile within this pipeline

2021-03-19 10:49 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
Ok, but it's not useless since it made it work (i think it search from this path recursively) but anyway i change it.

2021-03-19 11:04 UTC, eliecharra commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
No the path is not recursive at all. It works since you call binaries using their path `dctlenv/bin/dctlenv`

2021-03-19 11:22 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +		PATH="$PATH:$HOME/"
Oh right my bad i forget about this change
I assume now i can update their path to only executable since i changed $PATH

2021-03-23 08:56 UTC, wbeuil requested changes
The rest seems good to me

2021-03-23 08:56 UTC, wbeuil commented on docs/ci_cd/guides/jenkins.mdx
> +You can also setup a scheduled job to detect drifts as they happen, in the screenshot below it schedules a driftctl run every hour
`scan every hour:`

2021-03-23 08:56 UTC, wbeuil commented on docs/ci_cd/guides/jenkins.mdx
> +Below you can find a full Jenkinsfile example with a complete GitOps workflow example and a run of driftctl.
`and a driftctl scan.`

2021-03-23 19:53 UTC, lotoussa commented on docs/ci_cd/guides/jenkins.mdx
> +Below you can find a full Jenkinsfile example with a complete GitOps workflow example and a run of driftctl.
I took these part from gitlabci documentation, we can also change the typo from them.

2021-03-26 08:53 UTC, wbeuil approved these changes

2021-03-30 09:04 UTC, sundowndev approved these changes

2021-03-30 11:53 UTC, eliecharra approved these changes

2021-03-30 12:05 UTC, merged