Terraform custom role
cloudskiff/driftctl-docs pull request #28
Opened 2021-03-29 14:35 UTC by wbeuil

A duplicate of @bertux PR for a custom read-only role written in HCL to apply with Terraform.

2021-03-29 15:26 UTC, sundowndev commented on docs/providers/aws/driftctl-aws-role.tf
> +  policy = data.aws_iam_policy_document.policy.json
Not sure if the `.json` was intentional

2021-03-29 15:27 UTC, sundowndev requested changes
The role definition seems to contain a typo

2021-03-29 15:30 UTC, wbeuil commented on docs/providers/aws/driftctl-aws-role.tf
> +  policy = data.aws_iam_policy_document.policy.json
Yes it is https://registry.terraform.io/providers/hashicorp/aws/2.34.0/docs/guides/iam-policy-documents#aws_iam_policy_document-data-source

2021-03-29 15:33 UTC, sundowndev approved these changes

2021-04-12 15:28 UTC, eliecharra commented on docs/providers/aws/authentication.mdx
> +You will find in the [driftctl-aws-role.tf](https://github.com/cloudskiff/driftctl-docs/blob/main/docs/providers/aws/driftctl-aws-role.tf) terraform file a custom role that you can assume.
Maybe we can embed the HCL code directly in the markdown with 
\`\`\`hcl ? Any reason to put it in a dedicated file ?

```hcl
data "aws_caller_identity" "current" {}
```

2021-04-12 15:28 UTC, eliecharra commented on docs/providers/aws/authentication.mdx
> +Find below steps to create our custom role:
I don't think this is very usefull to explain how to use terraform there

2021-04-12 15:44 UTC, wbeuil commented on docs/providers/aws/authentication.mdx
> +You will find in the [driftctl-aws-role.tf](https://github.com/cloudskiff/driftctl-docs/blob/main/docs/providers/aws/driftctl-aws-role.tf) terraform file a custom role that you can assume.
Didn't know there was a ```hcl shortcut for that. Anyway yes of course we can, @sjourdan  any thoughts on this one ?

2021-04-12 15:49 UTC, wbeuil commented on docs/providers/aws/authentication.mdx
> +You will find in the [driftctl-aws-role.tf](https://github.com/cloudskiff/driftctl-docs/blob/main/docs/providers/aws/driftctl-aws-role.tf) terraform file a custom role that you can assume.
One problem I have in mind is that the page will increase as time passes by since we'll need to add permissions to it. Would we want to have a huge page to scroll or a simple file to fork ?

2021-04-12 15:50 UTC, wbeuil commented on docs/providers/aws/authentication.mdx
> +Find below steps to create our custom role:
We explained how to use the CloudFormation template, I guessed it would make sense to explain how to use the terraform one.

2021-04-13 07:28 UTC, sjourdan commented on docs/providers/aws/authentication.mdx
> +You will find in the [driftctl-aws-role.tf](https://github.com/cloudskiff/driftctl-docs/blob/main/docs/providers/aws/driftctl-aws-role.tf) terraform file a custom role that you can assume.
both serve a different purpose IMHO

In the context of a user reading documentation, I think it makes more sense to add it inline using ```hcl than pointing to a file.

Like (random example): https://www.terraform.io/docs/language/meta-arguments/depends_on.html

If really it becomes too long and unmanageable in the long run for general readability, we can still either use a dedicated section for it or use a folding section 

<details>
<summary>UNFOLD ME</summary>

```hcl
module "route53_records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "1.9.0"
  # insert the 2 required variables here
  zone_name = "wtf.co.uk"
  records = [
      {
          name = "lala"
          type = "A"
          ttl = 3600
          records = [
              "1.2.3.4",
          ]
      }
  ]
}
```
</detail>

2021-04-13 09:18 UTC, wbeuil commented on docs/providers/aws/authentication.mdx
> +Find below steps to create our custom role:
Remove in my last commit 41e9142

2021-04-13 09:18 UTC, wbeuil commented on docs/providers/aws/authentication.mdx
> +You will find in the [driftctl-aws-role.tf](https://github.com/cloudskiff/driftctl-docs/blob/main/docs/providers/aws/driftctl-aws-role.tf) terraform file a custom role that you can assume.
Done 41e9142

2021-04-13 09:22 UTC, eliecharra approved these changes

2021-04-13 09:23 UTC, merged