Strict mode documentation
cloudskiff/driftctl-docs pull request #41
Opened 2021-04-12 15:49 UTC by sundowndev

2021-04-12 16:04 UTC, eliecharra requested changes

2021-04-12 16:04 UTC, eliecharra commented on docs/usage/flags/strict-mode.mdx
> +id: strict-mode
As it is a flag of the scan `cmd`, we should move it in the scan page like other flags IMHO

![image](https://user-images.githubusercontent.com/6154987/114425171-1d6efc80-9bb9-11eb-8250-ca34fd4bb309.png)

`Flags` section is for global flags only

2021-04-12 16:04 UTC, eliecharra commented on versioned_docs/version-0.7.1/usage/flags/strict-mode.mdx
> +When running driftctl against an AWS account in an organization you may experience unnecessary noise with resources that don't belong to you. It can be default AWS security groups, or policy attachme
> It can be default AWS security groups

⚠️ No, strict flag will not change default resources behavior

2021-04-12 16:04 UTC, eliecharra commented on versioned_docs/version-0.7.1/usage/flags/strict-mode.mdx
> +When running driftctl against an AWS account in an organization you may experience unnecessary noise with resources that don't belong to you. It can be default AWS security groups, or policy attachme
> It's actually not a best practice to manage those resources in your own state.

Not really, you can manage theses resources in your state and that's totally fine.

2021-04-12 16:15 UTC, eliecharra commented
We should talk about service roles and detail in this section of documentation and put a list of what is ignored

2021-04-12 16:16 UTC, wbeuil requested changes
Don't forget to change the docs for the `/v0.7.1` once we agree on the wording.

2021-04-12 16:16 UTC, wbeuil commented on docs/usage/flags/strict-mode.mdx
> +When running driftctl against an AWS account in an organization you may experience unnecessary noise with resources that don't belong to you. It can be default AWS security groups, or policy attachme
It's not entirely true what you wrote.

`When running driftctl against an AWS account, you may experience unnecessary noises with resources that don't belong to you. It can be the case if you have an organization account in which you will by default have a service-linked role associated to your account (e.g. AWSServiceRoleForOrganizations). For now, driftctl ignores those service-linked resources by default.`

2021-04-12 16:16 UTC, wbeuil commented on docs/usage/flags/strict-mode.mdx
> +You could either add those resources in your driftignore file to ignore them, or simply let the tool decide what's important to report. If you still want to include those resources in the report anyw
I would remove the first sentence.

2021-04-12 16:17 UTC, wbeuil commented on docs/usage/flags/strict-mode.mdx
> +When running driftctl against an AWS account in an organization you may experience unnecessary noise with resources that don't belong to you. It can be default AWS security groups, or policy attachme
ping @eliecharra

2021-04-12 16:39 UTC, eliecharra approved these changes

2021-04-13 07:50 UTC, wbeuil requested changes

2021-04-13 07:50 UTC, wbeuil commented on docs/usage/cmd/scan.mdx
> +When running driftctl against an AWS account in an organization you may experience unnecessary noise with resources that don't belong to you. It can be the case if you have an organization account in
Still wrong, just copy/paste this:

`When running driftctl against an AWS account, you may experience unnecessary noises with resources that don't belong to you. It can be the case if you have an organization account in which you will by default have a service-linked role associated to your account (e.g. AWSServiceRoleForOrganizations). For now, driftctl ignores those service-linked resources by default.`

2021-04-13 07:50 UTC, wbeuil commented on docs/usage/cmd/scan.mdx
> +For now, concerned resources include :
`For now, resources include:`, no space before the colons.

2021-04-13 09:19 UTC, merged