Add telemetry doc
cloudskiff/driftctl-docs pull request #49
Opened 2021-04-28 08:25 UTC by eliecharra

Related to https://github.com/cloudskiff/driftctl/issues/441

2021-04-28 12:46 UTC, sundowndev commented on docs/usage/flags/disable-telemetry.mdx
> +By default, driftctl checks send some telemetry data to help us improve the product.
Not sure what you mean by "driftctl checks" ?

2021-04-28 13:18 UTC, eliecharra commented on docs/usage/flags/disable-telemetry.mdx
> +By default, driftctl checks send some telemetry data to help us improve the product.
Fixed

2021-04-28 14:05 UTC, sundowndev approved these changes

2021-05-03 08:25 UTC, wbeuil requested changes

2021-05-03 08:25 UTC, wbeuil commented on docs/usage/flags/disable-telemetry.mdx
> +By default, driftctl send some telemetry data to help us improve the product.
`driftctl sends telemetry data to ...`

2021-05-03 08:25 UTC, wbeuil commented on docs/usage/flags/disable-telemetry.mdx
> +You can find below a sample of data.
`You can find below a sample of what the data are.`

2021-05-03 09:50 UTC, wbeuil approved these changes

2021-05-03 09:54 UTC, merged