Issue 555: Add config-dir flag doc
cloudskiff/driftctl-docs pull request #69
Opened 2021-06-14 10:24 UTC by lotoussa

https://github.com/cloudskiff/driftctl/issues/555

2021-06-14 10:31 UTC, sundowndev requested changes

2021-06-14 10:31 UTC, sundowndev commented on docs/usage/flags/config-dir.mdx
> +This can be used for example to avoid the absence of home in an amazon lambda.
May be you add also add a statement about the env var `DCTL_CONFIG_DIR`

2021-06-14 10:55 UTC, sundowndev approved these changes

2021-06-14 12:38 UTC, wbeuil requested changes

2021-06-14 12:38 UTC, wbeuil commented on sidebars.js
> +          ],
This is not a global flag but a command flag just like `--from` or `--to`. You need to write it under `https://docs.driftctl.com/next/usage/cmd/scan-usage`

2021-06-14 12:38 UTC, wbeuil commented on docs/usage/flags/config-dir.mdx
> +title: Config Directory
`Configuration Directory`

2021-06-14 13:53 UTC, lotoussa commented on docs/usage/flags/config-dir.mdx
> +title: Config Directory
But i must delete this file if i move the documentation in usage/cmd/scan-usage right ?

2021-06-14 14:08 UTC, wbeuil commented on docs/usage/flags/config-dir.mdx
> +title: Config Directory
Yes, once you put it under the right folder, I want you to change the title.

2021-06-21 14:12 UTC, wbeuil requested changes

2021-06-21 14:12 UTC, wbeuil commented on sidebars.js
> +          ],
Can you checkout this file please?

2021-06-21 14:12 UTC, wbeuil commented on docs/usage/cmd/scan.mdx
> +This can be used for example to avoid the absence of home in an amazon lambda.
This can be useful, for example, if you want to invoke driftctl in an AWS Lambda function where you can only use the `/tmp` folder.

2021-06-21 14:16 UTC, lotoussa commented on sidebars.js
> +          ],
Ok

2021-06-21 14:34 UTC, wbeuil approved these changes

2021-06-21 14:34 UTC, merged