Add a different authentication mechanism for S3 bucket
cloudskiff/driftctl-docs pull request #83
Opened 2021-07-05 13:00 UTC by lotoussa

https://github.com/cloudskiff/driftctl/pull/671

Is this the good place in the doc to add this content ?

2021-07-05 14:46 UTC, sundowndev requested changes
May be we could add an example for the region as well

2021-07-05 14:46 UTC, sundowndev commented on docs/usage/cmd/scan.mdx
> +$ export DCTL_S3_AWS_PROFILE="<aws_profile_name>"
Isn't it `DCTL_S3_PROFILE` instead ?

2021-07-05 15:25 UTC, lotoussa commented on docs/usage/cmd/scan.mdx
> +$ export DCTL_S3_AWS_PROFILE="<aws_profile_name>"
sure, i change it

2021-07-05 15:30 UTC, sundowndev approved these changes

2021-07-05 15:44 UTC, sundowndev requested changes

2021-07-05 15:44 UTC, sundowndev commented on docs/usage/cmd/scan.mdx
> +# You can also change the region to s3 authentication and some more
I think this sentence make more sense `You can also use a specific region to authenticate to the S3 bucket`

2021-07-05 16:08 UTC, sundowndev approved these changes

2021-07-06 09:58 UTC, wbeuil requested changes
I would have put it under `/providers/aws/authentication` right before the `Terraform custom role` section with this explanation:

# Custom credentials to read a state on an S3 backend

If you want to use a different set of AWS credentials to read your state on S3, you can override each specific AWS environment variable with the DCTL_S3_ prefix. The purpose here is to have the choice to read a state in a different region than your infrastructure. Please don't forget to use your usual AWS credentials to read the resources of your actual infrastructure.

```
# Export a dedicated AWS named profile (or any other AWS environment variables) to read your state in your S3 backend
$ export DCTL_S3_PROFILE="s3reader"
# Export the usual driftctl AWS named profile
$ export AWS_PROFILE="driftctlrole"
$ driftctl scan --from tfstate+s3://mybucket/terraform.tfstate

# You can also use a specific region to authenticate to the S3 bucket
$ DCTL_S3_REGION=us-east-1 driftctl scan --from tfstate+s3://mybucket/terraform.tfstate
```

2021-07-06 12:12 UTC, lotoussa commented
> I would have put it under `/providers/aws/authentication` right before the `Terraform custom role` section with this explanation:
> 
> # Custom credentials to read a state on an S3 backend
> If you want to use a different set of AWS credentials to read your state on S3, you can override each specific AWS environment variable with the DCTL_S3_ prefix. The purpose here is to have the choice to read a state in a different region than your infrastructure. Please don't forget to use your usual AWS credentials to read the resources of your actual infrastructure.
> 
> ```
> # Export a dedicated AWS named profile (or any other AWS environment variables) to read your state in your S3 backend
> $ export DCTL_S3_PROFILE="s3reader"
> # Export the usual driftctl AWS named profile
> $ export AWS_PROFILE="driftctlrole"
> $ driftctl scan --from tfstate+s3://mybucket/terraform.tfstate
> 
> # You can also use a specific region to authenticate to the S3 bucket
> $ DCTL_S3_REGION=us-east-1 driftctl scan --from tfstate+s3://mybucket/terraform.tfstate
> ```

I agree, that was my first thought, i'm on it.

2021-07-06 13:23 UTC, wbeuil approved these changes

2021-07-06 13:24 UTC, merged