Add documetation about deep mode
cloudskiff/driftctl-docs pull request #85
Opened 2021-07-20 12:24 UTC by eliecharra

![image](https://user-images.githubusercontent.com/6154987/126323270-3d4ef6fc-c5a6-4fc2-bc58-ff8b72577320.png)

2021-07-20 13:01 UTC, sundowndev approved these changes

2021-07-20 13:33 UTC, lotoussa approved these changes

2021-07-22 09:02 UTC, wbeuil requested changes

2021-07-22 09:02 UTC, wbeuil commented on docs/usage/cmd/scan.mdx
> +In driftctl version < 0.13 the deep mode was the default behavior. If you want to keep the old behavior in the newer version you have to enable the deep mode flag.
`If you use a version of driftctl prior to 0.13, the deep ...`
`in a newer version ...`

2021-07-22 09:17 UTC, eliecharra commented on docs/providers/github/resources.mdx
> -- [x] github_membership
Nice catch

2021-07-22 13:57 UTC, wbeuil requested changes

2021-07-22 13:57 UTC, wbeuil commented on docs/usage/cmd/scan.mdx
> +In **non-deep** (the default one) we only enumerate resources and display which ones are out of IaC scope.
Can you add the word `mode` just after non-deep to emphasize what it actually is?

2021-07-22 13:57 UTC, wbeuil commented on docs/usage/cmd/scan.mdx
> +Since it overlaps the new terraform plan behavior (as of Terraform 0.15 it shows diffs between your state and the remote) we moved the original behavior under the `--deep` **experimental** flag.
Put the command `terraform plan` between backticks.

2021-07-22 14:04 UTC, wbeuil approved these changes

2021-07-22 14:26 UTC, wbeuil approved these changes

2021-07-22 14:39 UTC, merged