Add google provider
cloudskiff/driftctl-docs pull request #92
Opened 2021-08-04 15:51 UTC by eliecharra

2021-08-04 16:01 UTC, eliecharra commented
The build is failing because of 

```
Error: You are trying to create client-side redirections to paths that do not exist:
- /0.14.0/providers/google/authentication
```

This is a chicken and egg issue ...

2021-08-24 13:51 UTC, wbeuil requested changes

2021-08-24 13:51 UTC, wbeuil commented on docs/providers/google/authentication.mdx
> +Just like the terraform provider, we retrieve config from [environment variables](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference).
`Just like the Terraform ..., we retrieve configuration from ...`

2021-08-24 13:51 UTC, wbeuil commented on docs/providers/google/authentication.mdx
> +If you want to use driftctl with deep mode, driftctl will also need to retrieve resources details and the **Cloud Asset Viewer** will not be enough.
`to retrieve details' resources and the ..`

2021-08-24 13:51 UTC, wbeuil commented on docs/providers/google/authentication.mdx
> +If you want to be able to get resources details you should setup the basic role [Viewer](https://cloud.google.com/iam/docs/understanding-roles#basic-definitions) on your project.
`.. to get the details you ...`

2021-08-25 13:03 UTC, wbeuil approved these changes
LGTM, but the build failed since we do not have an actual `/0.14.0/providers/google/authentication` page.

We should wait for it to be in production before adding the redirection.

2021-08-30 12:36 UTC, merged